include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    use_build_context_synchronously: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - "**/test/**.mocks.dart"
  errors:
    todo: ignore
    always_declare_return_types: error
    missing_required_param: error
    parameter_assignments: warning
    missing_return: error
    unnecessary_non_null_assertion: error
    library_private_types_in_public_api: ignore
    use_key_in_widget_constructors: ignore